project:
  type: book
  pre-render: make quarto-prerender

book:
  title: "Dyndoc via Quarto"
  author: "Josh Errickson"
  date: date-modified
  chapters:
    - index.qmd
    - stata.qmd
    - r.qmd

format:
  html:
    theme: flatly # Choose from https://bootswatch.com
    css: style.css
